[{
	"resource": "/C:/Users/ragud/Downloads/qrworld-final-release-candidate/components/qr/page.tsx",
	"owner": "typescript",
	"code": "2614",
	"severity": 8,
	"message": "Module '\"@/components/qr/QrGeneratorForm\"' has no exported member 'QrGeneratorForm'. Did you mean to use 'import QrGeneratorForm from \"@/components/qr/QrGeneratorForm\"' instead?",
	"source": "ts",
	"startLineNumber": 4,
	"startColumn": 10,
	"endLineNumber": 4,
	"endColumn": 25,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/ragud/Downloads/qrworld-final-release-candidate/components/qr/page.tsx",
	"owner": "typescript",
	"code": "2322",
	"severity": 8,
	"message": "Type '{ userId: string; refreshKey: number; }' is not assignable to type 'IntrinsicAttributes & Props'.\n  Property 'userId' does not exist on type 'IntrinsicAttributes & Props'.",
	"source": "ts",
	"startLineNumber": 27,
	"startColumn": 24,
	"endLineNumber": 27,
	"endColumn": 30,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/ragud/Downloads/qrworld-final-release-candidate/app/globals.css",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": "unknownAtRules",
	"severity": 4,
	"message": "Unknown at rule @tailwind",
	"source": "css",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 10,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/ragud/Downloads/qrworld-final-release-candidate/app/globals.css",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": "unknownAtRules",
	"severity": 4,
	"message": "Unknown at rule @tailwind",
	"source": "css",
	"startLineNumber": 2,
	"startColumn": 1,
	"endLineNumber": 2,
	"endColumn": 10,
	"modelVersionId": 14,
	"origin": "extHost1"
},{
	"resource": "/C:/Users/ragud/Downloads/qrworld-final-release-candidate/app/globals.css",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": "unknownAtRules",
	"severity": 4,
	"message": "Unknown at rule @tailwind",
	"source": "css",
	"startLineNumber": 3,
	"startColumn": 1,
	"endLineNumber": 3,
	"endColumn": 10,
	"modelVersionId": 14,
	"origin": "extHost1"
}]